apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prep
  labels:
    app: app-prep
spec:
  template:
    metadata:
      labels:
        app: app-prep
    spec:
      containers:
        - name: app-prep
          image: restaurant-preparation:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-prep-credentials
                  key: username
            - name: MONGODB_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mongo-prep-credentials
                  key: password
            - name: ConnectionStrings__MongoDb
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongo-prep:27017"
            - name: Security__PublicKey
              valueFrom:
                secretKeyRef:
                  name: id-keys
                  key: public
            - name: ExternalServices__Identification
              value: "http://app-id"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  selector:
    matchLabels:
      app: app-prep
  replicas: 2
