apiVersion: v1
kind: Secret
metadata:
  name: mongo-prep-credentials
type: Opaque
stringData:
  username: mongoprepuser
  password: 60febe5875ac4aa48f82d70276f9b0c2
  connectionString: mongodb://mongoprepuser:60febe5875ac4aa48f82d70276f9b0c2@mongo-order:27017