<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Preparation.Application\Restaurant.Preparation.Application.csproj" />
    <ProjectReference Include="..\Restaurant.Preparation.Data\Restaurant.Preparation.Data.csproj" />
  </ItemGroup>

</Project>
